project:
  type: website
  output-dir: docs
  execute-dir: project
  pre-render: scripts/generate_data.R
  render:
    - index.qmd
    - "chapters/*.qmd"
    - "data/*.qmd"
  resources:
    - components/

filters:
  - filters/number-sections.lua

website:
  title: "Data Literacy"
  site-url: "https://dev.dataliteracy.cc"
  sidebar:
    style: "docked"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Home"
      - href: chapters/curriculum.qmd
        text: "Curriculum & Skill Tree"
      - href: data/datasets.qmd
        text: "Datasets"
      - section: "Computational Skills"
        contents:
          - chapters/1.01-basic-computer-skills.qmd
          - chapters/1.02-r-language.qmd
          - chapters/1.03-reproducible-reports.qmd
      - section: "Data Management"
        contents:
          - chapters/2.01-data-frames.qmd
          - chapters/2.02-grouping-and-summarizing.qmd
          - chapters/2.03-data-cleaning.qmd
          - chapters/2.04-pivoting-and-joining.qmd
          - chapters/2.05-string-processing.qmd
      - section: "Statistical Foundations"
        contents:
          - chapters/3.01-means-and-variance.qmd
          - chapters/3.02-probability-and-sampling.qmd
          - chapters/3.03-correlation-and-covariance.qmd
          - chapters/3.04-effects.qmd
          - chapters/3.05-hypothesis-testing.qmd
      - section: "Exploration and Measurement"
        contents:
          - chapters/4.01-descriptive-statistics.qmd
          - chapters/4.02-data-visualization.qmd
          - chapters/4.03-advanced-visualization.qmd
          - chapters/4.04-factor-analysis.qmd
          - chapters/4.05-scale-construction.qmd
      - section: "Inferential Statistics"
        contents:
          - chapters/5.01-comparing-two-groups.qmd
          - chapters/5.02-testing-associations.qmd
          - chapters/5.03-linear-models.qmd
          - chapters/5.04-anova.qmd
          - chapters/5.06-regression.qmd
          - chapters/5.08-linear-model-assumptions.qmd
          - chapters/5.09-power-analysis.qmd
      - section: "Causality"
        contents:
          - chapters/3.06-causality.qmd
          - chapters/5.05-experimental-control.qmd
          - chapters/5.07-statistical-control.qmd
          - chapters/5.10-mediation-analysis.qmd
      - section: "Content Analysis"
        contents:
          - chapters/6.01-text-as-data.qmd
          - chapters/6.02-manual-coding.qmd
          - chapters/6.03-machine-learning.qmd
          - chapters/6.04-text-classification.qmd

bibliography: references/references.bib
cls: references/apa7.cls

format:
  html:
    df-print: paged
    theme:
      - flatly
      - style.scss
    fontsize: 0.9em
    toc: true
    number-sections: false

engine: knitr
