project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy"
  references: references/references.bib
  llms-txt: true
  sidebar:
    collapse-level: 2
    style: "docked"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - chapters/01-data-literacy.qmd
        - chapters/02-curriculum.qmd
        - chapters/03-research-traditions.qmd
    - part: "Digital Literacy"
      chapters:
        - chapters/04-working-with-r.qmd
        - chapters/05-projects.qmd
        - chapters/06-quarto.qmd
    - part: "Data Management"
      chapters:
        - chapters/07-data-frames.qmd
        - chapters/08-data-cleaning.qmd
        - chapters/09-transformations.qmd
        - chapters/10-factor-analysis.qmd
        - chapters/11-scale-construction.qmd
    - part: "Data Analysis"
      chapters:
        - chapters/12-descriptive-statistics.qmd
        - chapters/13-visualization.qmd
        - chapters/14-statistical-tests-overview.qmd
    - part: "Statistical Tests"
      chapters:
        - chapters/15-chi-square.qmd
        - chapters/16-t-test.qmd
        - chapters/17-correlation.qmd
        - chapters/18-linear-regression.qmd
        - chapters/19-anova.qmd
        - chapters/20-ancova.qmd
  appendices:
    - chapters/21-hypothesis-testing.qmd
    - chapters/22-causality.qmd

bibliography: references/references.bib
cls: references/apa7.cls

language:
  section-title-appendices: "Concepts"

crossref:
  appendix-title: " "
  # appendix-delim: ""

# Light/General: default, cerulean, cosmo, flatly,
# journal, litera, lumen, lux, materia, minty, morph,
# pulse, quartz, sandstone, simplex, sketchy,
# spacelab, united, yeti, zephyr.
# Dark: cyborg, darkly, slate, solar, superhero, vapor.

format:
  live-html:
    theme:
      - flatly
      - style.scss
    fontsize: 0.9em
    toc: true
    number-sections: true
    number-depth: 2

engine: knitr

execute:
  freeze: auto
