---
title: Getting Started
order: 1
---

In the VU Communication Science track, you'll be using the **R statistical software** as a tool for learning quantitative methods and data analysis techniques. 
R is a powerful, open-source programming language that is widely used in academia and industry for statistical analysis, visualization, text analysis, and more. 

Through our courses, you'll get hands-on experience with R, allowing you to analyze real-world data, perform statistical tests, create insightful visualizations, and develop reproducible research workflows. These skills will be invaluable as you move forward in your studies and future career, where data-driven decision-making plays a crucial role.

R is also open-source, and therefore free to use for both academic and commercial purposes. This means you can continue to use R beyond your studies without any licensing costs, giving you the flexibility to apply your skills in various professional settings. The open-source nature of R also fosters a vibrant community of users and contributors who regularly share packages, tutorials, and resources. This community support makes it easier to find help, learn new techniques, and stay updated with the latest developments in data science and statistical analysis.

In this **Getting started** section, we'll walk you through your first steps. We will cover how to install R, how to install and use the RStudio software for working with R, and the basics of the R syntax.