{
  "hash": "4af911c7da825b534560d07538bd86b1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Correlation analysis\"\n---\n\n## What is the correlation test?\n\nThe correlation test can be used to see if there is `a relationship between two numeric variables`.\nFor example, we might want to know if there is a relationship between the amount of time people spend on social media and their feelings of loneliness.\n\nThe relation is expressed as a measure (the correlation coefficient) on a scale from -1 to 1, that tells us how strong the relationship is, and whether it is positive or negative.\nWe also get a p-value that tells us if the relationship is significant.\nIn this tutorial we focus on conducting the test. For more details on the concept of correlation and how to interpret the correlation coefficient $r$, see the [covariance and correlation](17-correlation.qmd) section.\n\nWhat the correlation test **does not** tell us is why the relationship exists.\nIf we find that there is a correlation between social media use and loneliness, it does not mean that social media use causes loneliness.\nFor more detail on this, see the [causality](22-causality.qmd) section.\n\n## How to use\n\nWe'll show two ways of conducting the correlation test: using the `cor.test` function and using the `tab_corr` function from the `sjPlot` package.\nThe `cor.test` function is part of the base R package, and is usefull if you just have two variables.\nThe `tab_corr` function is part of the `sjPlot` package, and is useful if you have multiple variables and want to see the correlations between all of them.\n\nTo demonstrate the correlation test, we'll use the practice data that we've used before.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nd <- read_csv(\"https://data.dataliteracy.cc/simulated/practice_data.csv\") |>\n        rename(news_consumption = `news consumption`)\n```\n:::\n\n\n### Between two variables: cor.test\n\nIn the practice data we have variables for the `news_consumption` of the participants, and their `trust_t1` in the news media (measured before the experiment).\nThese are both numeric variables, so we can use the correlation test to see if there is a relationship between them. \n\nTo perform the correlation test using the `cor.test` function, we pass the two variables to the function.\nRecall that we can use the `$` symbol to access variables in a data frame.\nSo here we access the `news_consumption` and `trust_t1` variables from the `d` data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(d$news_consumption, d$trust_t1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  d$news_consumption and d$trust_t1\nt = 5.8832, df = 598, p-value = 6.702e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1567994 0.3081822\nsample estimates:\n     cor \n0.233908 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThe output gives us the correlation coefficient under the `sample estimates`, which in our case is $r = 0.234$.\nThis means that the correlation is positive (> 0), but quite weak.\nThe test also reports a p-value (0.000), which tells us that the correlation is significant at the $95\\%$ (`< 0.05`) confidence level. \nAlso note that the degrees of freedom are reported as 598, which is the number of observations minus 2.\n\n::: {.callout-note title=\"cor.test using the formula notation\" collapse=\"true\"}\n\nIt is also possible to use the formula notation in the `cor.test` function.\nHowever, this looks a bit weird, because in the correlation tests there are no dependent variables, since we are **just looking at the relationship**.\nThe convention for formulas in R is to use the `~` symbol to separate the dependent and independent variables (`dependent ~ independent_1 + independent_2 + ...`).\nFor the correlation test, we would just omit the dependent variable.\nSo for the example above, the code would look like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(~ news_consumption + trust_t1, data = d)\n```\n:::\n\n:::\n\n### Between more variables: tab_corr\n\nIf we need to see the correlations between multiple variables, we can use the `tab_corr` function from the `sjPlot` package.\nFor example, let's look at the correlations between the 5 items used to calculate the `trust_t1` scale.\nTo use `tab_corr`, we can simply pass a data frame with the variables we want to use.\nHere we use the `select` function to select all columns from `trust_t1_item1` to `trust_t1_item5`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sjPlot)\nd |>\n    select(trust_t1_item1:trust_t1_item5) |>\n    tab_corr()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">&nbsp;</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">trust_t1_item1</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">trust_t1_item2</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">trust_t1_item3</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">trust_t1_item4</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">trust_t1_item5</th>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">trust_t1_item1</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.328<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.739<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.727<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.827<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">trust_t1_item2</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.328<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.288<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.264<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.324<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">trust_t1_item3</td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.739<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.288<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.677<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.770<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">trust_t1_item4</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.727<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.264<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.677<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.759<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">trust_t1_item5</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.827<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.324<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.770<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.759<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td colspan=\"6\" style=\"border-bottom:double black; border-top:1px solid black; font-style:italic; font-size:0.9em; text-align:right;\">Computed correlation used pearson-method with listwise-deletion.</td>\n</tr>\n \n</table>\n`````\n:::\n:::\n\n\nThis is great for getting a quick overview of the relationships between multiple variables.\nIf you need to get the exact p-values, you can also use `tab_corr(p.numeric = TRUE)`.\n\n\n## Conditions and assumptions\n\nThe correlation test can be used when you have two `numeric` variables and you want to know if there is a relationship between them.\nThere is no `dependent` or `independent` variable in the correlation test, because we are just looking at the relationship between the variables.   \n\nThere are four main conditions that need to be met for the correlation test to be valid:\n\n1. **Continuous variables**: Both variables should be numeric, and measured on a interval or ratio scale.\n2. **Linearity**: The relationship between the variables should be linear.\n3. **Normality**: The variables should be (roughly) normally distributed. \n4. **No outliers**: Extreme values can have a big impact on the correlation coefficient.\n\nIf these conditions are not met, you might want to use Spearman's $\\rho$ or Kendall's $\\tau$ instead of the Pearson correlation coefficienta\nSpearman's $\\rho$ looks as the rank order of the variables instead of the specific scores, which makes it suitable for ordinal data, and makes it more robust to outliers, non-linear relationships, and non-normality.\nKenall's $\\tau$ is similar to Spearman's $\\rho$, but can be preferable if there are many ties in the data (when two or more observations have the same value, due to which they can't be ranked perfectly).\n\n### Spearman's $\\rho$ and Kendall's $\\tau$\n\nTo use the Spearman's $\\rho$ or Kendall's $\\tau$ correlation, you need to specify the `method` argument in the `cor.test` function, or the `corr.method` argument in the `tab_corr` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(d$news_consumption, d$trust_t1, method = \"spearman\")\ncor.test(d$news_consumption, d$trust_t1, method = \"kendall\")\n\nd |> select(trust_t1_item1:trust_t1_item5) |> tab_corr(corr.method=\"spearman\")\nd |> select(trust_t1_item1:trust_t1_item5) |> tab_corr(corr.method=\"kendall\")\n```\n:::\n\n\n\n## How to report\n\nFor APA style reporting of the correlation test you need to know the `correlation coefficient`, `p-value`, and the `degrees of freedom`. \nYou can find all these values in the output of the `cor.test` function.[^1] \n\n[^1]: When using `tab_corr`, you can use the `p.numeric = TRUE` argument to get the p-values.\nThe degrees of freedom is always the number of observations minus 2, but be carefull not to count missing (NA) values.  \n\nThe formula for reporting the results of a correlation test in APA style is:\n\nr(`degrees of freedom`) = `correlation coefficient`, p = `p-value`.\n\n* the `correlation coefficient` is rounded to two decimal places, and the number before the decimal point is ommited if zero (`.11` instead of `0.11`).\n* The `p-value` is reported for the smallest significant level (`p < 0.05`, `p < 0.01` or `p < 0.001`), or in full with three decimal places if not significant (`p = 0.123`).\n\n\n\nFor example, if we observe a correlation coefficient of $r = 0.107$ with a p-value of $p = 0.009$, and $298$ degrees of freedom. \nWe would report this as:\n\n> There is a positive correlation between age and trust in journalists, $r(298) = .12$, $p < 0.01$.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}