{
  "hash": "a8ef900c08e36bc8580bff20d30c344c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ANCOVA\"\n---\n\n## What is ANCOVA?\n\nIn a previous chapter we introduced ANOVA (Analysis of Variance) as a method to test whether group means differ significantly. ANOVA works well when the dependent variable is (hypothesized to be) influenced only by the independent variable(s). In practice, however, outcomes are often influenced by additional variables that are not part of the experimental manipulation. For example:\n\n-   Students may differ in prior knowledge;\n-   Participants may differ in age;\n-   Individuals may differ in motivation.\n\nSuch variables introduce extra variability in the dependent variable.\n\n**ANCOVA (Analysis of Covariance)** extends ANOVA by including a continuous control variable, called a *covariate*. In short, ANCOVA does the same as ANOVA, which is comparing group means, while additionally controlling for another variable. Conceptually, ANCOVA sits at the intersection of ANOVA and linear regression.\n\n### When do we use ANCOVA?\n\nANCOVA is useful for two reasons:\n\n#### 1. Controlling for confounding variables\n\nA covariate may influence the dependent variable but is not the main variable of interest. For example: If we compare learning outcomes across teaching methods, students’ prior knowledge may influence the outcome. Including 'prior knowledge' as a covariate allows us to compare teaching methods *while holding prior knowledge constant.*\n\n##### 2. Reducing unexplained variance\n\nEven if the covariate is not a *confounder*, it may still explain part of the outcome variability. Accounting for this variability reduces residual variance, which can increase statistical power.\n\n#### What happens to variance when adding a covariate?\n\nRecall from the ANOVA chapter that total variability in the dependent variable is partitioned into:\n\n-   **between-group variance** (explained by the independent variable)\n-   **within-group variance** (unexplained error)\n\nWhen we add a *covariate* in ANCOVA, part of the variability that was previously counted as **within-group error** is now explained by the covariate!\n\nThis has two important consequences:\n\n-   The **within-group variance decreases**, because the covariate accounts for systematic differences between individuals;\n-   As a result, the **signal-to-noise ratio increases**, making it easier to detect differences between groups!\n\nConceptually, ANCOVA “cleans up” the error term by removing variance that is not relevant to the group comparison and turns it into explained variance, which increases statistical power.\n\nImportantly, the **between-group variance is now evaluated after adjusting for the covariate**. This means that group differences reflect differences **over and above the effect of the covariate**.\n\n## How to use it\n\nSuppose we study whether different *robot designs* influence *how comfortable people feel interacting with a robot*. Participants interact with one of three robots: 'Alice', 'Nao' and 'Robocop'. They then report their comfort level.\n\nHowever, participants also differ in their *familiarity with robots*, which may affect comfort ratings, regardless of the robot design they were presented with! We might expect that participants who are more familiar with robots feel more comfortable interacting with them. We therefore include robot familiarity as a *covariate* to control for this.\n\n\n::: {.cell}\n\n:::\n\n\nBefore we proceed with any analysis, we load relevant packages, import the dataset and inspect the variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: no DISPLAY variable so Tk is not available\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(afex)\nlibrary(emmeans)\nlibrary(sjPlot)\n```\n:::\n\n\n``` {eval=\"FALSE\"}\nsetwd()\nrobot_data <- read_csv(\"robot_data.csv\")\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrobot_data |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  robot_design interaction_type  familiarity         comfort      \n Alice  :80    Touch:120        Min.   : 0.3817   Min.   : 1.720  \n Nao    :80    Voice:120        1st Qu.: 3.7378   1st Qu.: 6.671  \n RoboCop:80                     Median : 4.8453   Median : 7.910  \n                                Mean   : 4.9892   Mean   : 7.926  \n                                3rd Qu.: 6.1368   3rd Qu.: 9.375  \n                                Max.   :11.4821   Max.   :14.059  \n       id        \n Min.   :  1.00  \n 1st Qu.: 60.75  \n Median :120.50  \n Mean   :120.50  \n 3rd Qu.:180.25  \n Max.   :240.00  \n```\n\n\n:::\n:::\n\n\n### One-way ANCOVA\n\nAny **one-way ANCOVA** includes:\n\n-   one categorical independent variable\n-   one covariate\n-   one continuous dependent variable\n\nIn our example, we consider the following design:\n\n-   IV = `robot_design` (Alice, Nao or Robocop)\n-   Covariate = `familiarity`\n-   DV = `comfort`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-ancova_files/figure-html/one-way-ancova-1-1.png){width=672}\n:::\n:::\n\n\nThe plot above indicates that there is indeed a linear relationship between `familiarity` and `comfort`, suggesting it's relevant to include the effect of one's (prior) familiarity with robots on their comfort level in the analysis.\n\nWe estimate the model using the function `aov_car()` from the `afex` package. For `Error()`, we specify that our individual cases can be distinguised by the variable `id`. After `observed =` with specify which independent variables in the model are observed, i.e.: not (experimentally) manipulated. In this context it's only our covariate `familiarity`. Finally, we specify `factorize = FALSE`, which means that we don't want R to turn our (numeric) covariate into a factor variable. With this we do assume, though, that our other independent variable(s) is/are correctly coded as factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_ancova <- aov_car(\n  comfort ~ robot_design + familiarity + Error(id),\n  data = robot_data,\n  observed = \"familiarity\", \n  factorize = FALSE\n)\n\nmodel_ancova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: comfort\n        Effect     df  MSE          F  ges p.value\n1 robot_design 2, 236 2.49    6.09 ** .034    .003\n2  familiarity 1, 236 2.49 105.94 *** .310   <.001\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_ancova$Anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: dv\n             Sum Sq  Df  F value    Pr(>F)    \n(Intercept)  779.45   1 312.9268 < 2.2e-16 ***\nrobot_design  30.32   2   6.0861  0.002647 ** \nfamiliarity  263.89   1 105.9417 < 2.2e-16 ***\nResiduals    587.84 236                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe model above tests whether whether robot designs differ in comfort (*F =* 6.09, *p* \\< 0.01) *and* whether familiarity predicts comfort (*F =* 105.94, *p* \\< 0.001). The effect of robot design has now been tested **while controlling for familiarity**.\n\n#### (Un)adjusted means\n\nBecause familiarity influences comfort, 'raw' group means could be misleading. ANCOVA therefore compares **adjusted means**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(model_ancova, \"robot_design\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n robot_design emmean    SE  df lower.CL upper.CL\n Alice          8.05 0.176 236     7.70     8.40\n Nao            8.29 0.177 236     7.94     8.63\n RoboCop        7.44 0.176 236     7.09     7.79\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThese means represent expected comfort levels if all participants had the *same level of familiarity*. By default, the covariate is held constant at its *sample mean* (here `4.99`) and group means are then estimated as if all participants had that same (average) level of familiarity. Let's compare that to the output below, showing the *unadjusted means* (from a 'regular' ANOVA model).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_anova <- aov_car(\n  comfort ~ robot_design + Error(id),\n  data = robot_data\n)\nemmeans(model_anova, \"robot_design\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n robot_design emmean    SE  df lower.CL upper.CL\n Alice          8.08 0.212 237     7.66     8.49\n Nao            8.24 0.212 237     7.82     8.66\n RoboCop        7.46 0.212 237     7.05     7.88\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThe plots below visualize the difference between adjusted and unadjusted means. The adjusted and unadjusted means are similar. We did, however find a substantial effect of the covariate on comfort (r = `sqrt(.310) = 0.56`). This suggests that the covariate `familiarity` explains a lot of individual variability between participants (within-group variance), but is *not* related to group membership! This is normal in an experimental settings, where we certainly do not expect to influence which robot design participants were presented with.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-ancova_files/figure-html/un-adjusted-means-3-1.png){width=672}\n:::\n:::\n\n\n### Assumptions of ANCOVA\n\nBesides the assumption of equal (error) variances that we've learned to test with the Levene's test, there are two additional assumptions to consider when performing an ANCOVA.\n\n#### Independence of the covariate\n\nThe covariate (here `familiarity`) **should not differ systematically between groups** of the grouping variable (`robot_design)`. We test for this assumption by estimating a model that studies whether there are differences in covariate means for the groups of the independent grouping variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov_indep <- aov_car(\n  familiarity ~ robot_design + Error(id),\n  data = robot_data,\n)\ncov_indep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: familiarity\n        Effect     df  MSE    F  ges p.value\n1 robot_design 2, 237 3.55 0.13 .001    .879\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe analysis suggests that there are no pre-existing differences in familiarity between robot design groups (*F* = 0.13, *p* \\> 0.05). The plot below supports and visualizes this conclusion: we observe that the three group means on familiarity (for Alice, Nao and Robocop) are approximately the same.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-ancova_files/figure-html/independence-of-the-covariate-2-1.png){width=672}\n:::\n:::\n\n\nShould familiarity strongly differ between groups, ANCOVA adjusts for pre-existing differences rather than purely isolating the effect of the independent variable. In randomized experiments this assumption is typically satisfied. In observational data it should be checked explicitly.\n\n#### Homogeneity of regression slopes\n\nThe assumption of homogeneity of regressino slopes suggests implies that the **relationship between the covariate and the dependent variable should be similar across groups**. We test for this by including the interactino between the covariate and the independent grouping variable in the model. If the interaction between the covariate and the factor is *not* significant, the assumption is likely satisfied.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_slopes <- aov_car(\n  comfort ~ robot_design * familiarity + Error(id),\n  data = robot_data,\n  observed = \"familiarity\",\n  factorize = FALSE\n)\n\nmodel_slopes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: comfort\n                    Effect     df  MSE          F  ges p.value\n1             robot_design 2, 234 2.51       0.61 .004    .546\n2              familiarity 1, 234 2.51 105.54 *** .310   <.001\n3 robot_design:familiarity 2, 234 2.51       0.22 .001    .803\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe interaction between `robot_design` and `familiarity` is not significant (*F* = 0.22, *p* \\> 0.05). There is no evidence that the assumption of homogeneity of regression lines is violated.\n\nThe plot that we've seen earlier in this chapter helps us visualize the outcomes of above assumption test, as we notice how the regression slopes for the different robot designs are almost parallel:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](20-ancova_files/figure-html/homogeneity-of-regression-slopes-2-1.png){width=672}\n:::\n:::\n\n\n### Two-way ANCOVA\n\nWe now **extend the model** by including interaction type as a *second factor*: the interaction type with the robot, which could be through *touch* or through *voice*. Participants have been divided 50/50 on this variable, which leads to 6 groups of 40 participants in the experiment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrobot_data |> freq(interaction_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \nrobot_data$interaction_type  \nType: Factor  \n\n              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------- ------ --------- -------------- --------- --------------\n      Touch    120     50.00          50.00     50.00          50.00\n      Voice    120     50.00         100.00     50.00         100.00\n       <NA>      0                               0.00         100.00\n      Total    240    100.00         100.00    100.00         100.00\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(robot_data$robot_design, robot_data$interaction_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Touch Voice\n  Alice      40    40\n  Nao        40    40\n  RoboCop    40    40\n```\n\n\n:::\n:::\n\n\nWe now include two independent grouping variables (`robot_design` and `interaction_type`) and a covariate (`familiarity`) in the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_two_way <- aov_car(\n  comfort ~ robot_design * interaction_type + \n    familiarity + Error(id),\n  data = robot_data,\n  observed = \"familiarity\", \n  factorize = FALSE\n)\n\nmodel_two_way\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: comfort\n                         Effect     df  MSE          F  ges p.value\n1                  robot_design 2, 233 2.36    6.43 ** .036    .002\n2              interaction_type 1, 233 2.36  15.54 *** .043   <.001\n3                   familiarity 1, 233 2.36 113.83 *** .328   <.001\n4 robot_design:interaction_type 2, 233 2.36       0.18 .001    .838\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_two_way$Anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: dv\n                              Sum Sq  Df  F value    Pr(>F)    \n(Intercept)                   769.89   1 325.9852 < 2.2e-16 ***\nrobot_design                   30.36   2   6.4272 0.0019186 ** \ninteraction_type               36.71   1  15.5436 0.0001067 ***\nfamiliarity                   268.84   1 113.8319 < 2.2e-16 ***\nrobot_design:interaction_type   0.84   2   0.1772 0.8376895    \nResiduals                     550.29 233                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis model tests\n\n-   the main effect of **robot design** (*F* = 6.43, *p* \\< 0.01);\n-   the main effect of **interaction type** (*F* = 15.54, *p* \\< 0.001);\n-   the **interaction** between the two (*F* = 0.18, *p* \\> 0.05); *and*\n-   the effect of the **covariate** (*F* = 113.83, *p* \\< 0.001).\n\nThe interpretation of main and interaction effects is identical to the two-way ANOVA discussed in the previous chapter. The key difference is that we now **control for familiarity**. Should we present estimated marginal means, `familiarity` would still be held constant at its sample mean.\n\n#### Comparing models\n\nTo understand how controlling for a covariate increases model explanatory power, we also perform a (two-way) ANOVA without the covariate. Let's then compare the Sum of Squares of the Residuals (RSS), i.e.: error variance, of both models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Two-way ANOVA\ntwoway_anova <- aov_car(\n  comfort ~ robot_design * interaction_type + Error(id),\n  data = robot_data\n)\n\ntwoway_anova$Anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: dv\n                               Sum Sq  Df   F value    Pr(>F)    \n(Intercept)                   15077.1   1 4307.0670 < 2.2e-16 ***\nrobot_design                     26.7   2    3.8131  0.023465 *  \ninteraction_type                 30.9   1    8.8310  0.003271 ** \nrobot_design:interaction_type     1.7   2    0.2407  0.786267    \nResiduals                       819.1 234                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Two-way ANCOVA\nmodel_two_way$Anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: dv\n                              Sum Sq  Df  F value    Pr(>F)    \n(Intercept)                   769.89   1 325.9852 < 2.2e-16 ***\nrobot_design                   30.36   2   6.4272 0.0019186 ** \ninteraction_type               36.71   1  15.5436 0.0001067 ***\nfamiliarity                   268.84   1 113.8319 < 2.2e-16 ***\nrobot_design:interaction_type   0.84   2   0.1772 0.8376895    \nResiduals                     550.29 233                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe error variance has decreased by `819.1 - 550.29 = 268.81` after indlucing the covariate `familiarity` in the model. This is the amount of variance now explained by the covariate.\n\n## Summary\n\nANCOVA extends ANOVA by including a **covariate**. The main takeaways of this chapter should be that ANCOVA...\n\n-   compares group means while controlling for a continuous variable;\n-   reduces unexplained variance and, as such, can increase statistical power;\n-   requires additional assumptions, which are independence of the covariate and homogeneity of regression slopes; and\n-   can be extended to factorial designs such as two-way ANCOVA.\n",
    "supporting": [
      "20-ancova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}