{
  "hash": "b9d202aca511713da22643a1c03fa679",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ANOVA\"\n---\n\n## What is an ANOVA?\n\nAnalysis of Variance, or ANOVA, is a statistical technique used to compare the means of several groups at once.\nANOVA tests whether any of the group means differ more than would be expected by random variation alone.\nThis makes it particularly suitable for experimental research, where participants are randomly assigned to different groups, and the researcher wants to know whether the groups differ on some outcome variable.\nBecause of the random assignment, all possible confounding variables should be equally distributed over the groups, which allows us to make causal inferences about the effect of the independent variable on the dependent variable.[^1]\n\n[^1]: It is also possible to use ANOVA with non-experimental (i.e. observational) data.\n    However, this limits our ability to make causal inferences.\n    For observational data it is more common to use [regression analysis](18-linear-regression.qmd), because this provides more flexibility to control for confounding variables.\n    (This is also possible with more advanced forms of ANOVA, like ANCOVA and MANOVA).\n\nThere are different types of ANOVA to cover a wide range of research designs.\nThe most common ones are:\n\n### One-way ANOVA\n\n-   **Purpose**. Compare means *between-subjects* in different groups.[^2]\n-   **Example**. We want to know how the design of a health care robot affects how *comfortable* people feel about interacting with the robot. To test this we *randomly* asign participants to three experimental groups, that are shown three different robot designs ([Alice, Nao](https://vu.nl/nl/onderzoek/meer-over/sociale-robots-voor-de-samenleving-mediapsychologie), and RoboCop). They then answer multiple questions based on which we measure a *comfort rating* [scale](11-scale-construction.qmd). We can now use One-way ANOVA to compare the mean comfort rating between the three groups.\n\n[^2]: This is similar to an independent samples t-test, but can be used for more than two groups.\n\n#### Two-way ANOVA\n\n-   **Purpose**. Compare means *between-subjects* in different groups, for two independent variables.\n-   **Example**. In addition to comparing three different designs of a health care robot, we could also compare between using a *male* or *female* voice. We then randomly assign participants to six groups (3 designs \\* 2 voices), and use two-way ANOVA to test whether the design and voice have an effect on the perceived attractiveness. We can then also test whether there is an *interaction* between the two variables, to see if specific combinations of design and voice are particularly comforting.\n\n#### Repeated measures ANOVA\n\n-   **Purpose**. Compare means *within-subjects* measured at different timepoints.[^3]\n-   **Example**. Instead of the self-reporting comfort rating, we could measure how people react to interacting with a health care robot by measuring their *heart rate*. We could then measure the *heart rate* of participants *before*, *during*, and *after* interacting with the robot. We can then use repeated measures ANOVA to compare the *heart rate* at each stage.\n\n[^3]: This is similar to a paired samples t-test, but can be used for more than two groups.\n    This is primarily used for within-subjects designs, where the same participants are measured multiple times.\n\n#### Mixed-design ANOVA\n\n-   **Purpose**. Combine *between-subjects* and *within-subjects* factors.\n-   **Example**. This allows us to measure simultaneously the effect of the design of a health care robot (one-way anova example) on the change in *heart rate* (repeated measures example). We divide participants into three groups that are shown the three different designs, and measure the *heart rate* of participants *before*, *during*, and *after* interacting with the robot. We can then use mixed-design ANOVA to test whether the three designs of a health care robot affect the change in hearthrate differently.\n\n```{=html}\n<!-- # How does it work\n\nUnderneath the hood, ANOVA is a linear model just like [regression analysis](18-linear-regression.qmd).\nIf you have not yet read the regression tutorial, you can skip this section, and focus first on how to use ANOVA in practice.\n\nYou can think of ANOVA as a special case of regression where the independent variables are categorical.\nIn the regression tutorial we showed you how you can use categorical independent variables in a regression model using dummy variables.\nYou might recall that it's not straightforward to compare all of the groups, or to test overall whether there is a difference between the groups.\nANOVA is a more specialized tool for this purpose.\n\nTo understand how ANOVA is *different* from *regular regression*, you need to understand two concepts.[^not_different]\n\n[^not_different]: We emphasize *different* and *regular regression*, because technically ANOVA is still just a type of regression. By different we here refer to how ANOVA and regression are most commonly used in our field.\n\n* **Contrast coding**. In regression we usually use **dummy coding** for categorical variables, which compares each group to a single reference group. But we can also use **effect coding** to compare each group to the *grand mean* (the mean of all groups). \n* **Sum of squares**. In a linear model we use sum of squares to assess how much variance is explained by the model. ANOVA allows using different types of sum of squares (Type I, II, III) for different purposes. In most cases researchers use Type III sums of squares (which is the default in popular statistics software like SPSS).\n\n\n\nIn the social sciences, when researchers use ANOVA, they usually use Type III sums of squares and effect coding. In popular statistics software like SPSS, this is also the default approach.\nIn this tutorial we will also stick to this default.\nBut as you'll see in the code, we do need to specify ourselves that we want to use Type II sums of squares and effect coding (specifically we'll use Helmert coding). -->\n```\n\n## How to use it\n\nWe'll use the `afex` and `emmeans` packages to perform ANOVA tests and compare means, and we'll use the `sjPlot` package to visualize the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(afex)\nlibrary(emmeans)\nlibrary(sjPlot)\n```\n:::\n\n\nFor our examples we'll use our [Practice data](07-data-frames.qmd#practice-data).\nIn this data have a (fictional) experiment where we study the effect of popular media on people's trust in journalists.\nSpecifically, we're using the following variables:\n\n-   **id**. A unique identifier for each participant.\n-   **experiment_group**. The group that participants were assigned to. Each group viewed a different movie that was either *neutral* (control), *positive*, or *negative* about journalism.\n-   **np_subscription**. Whether participants have a subscription to a national newspaper, with values *yes* or *no*.\n-   **trust_t1** and **trust_t2**. The trust in journalists, measured before (t1) and after (t2) watching a movie about journalism.\n\nThe **experiment_group** and **np_subscription** variables are our independent variable.\nTo use these in the ANOVA, we'll explicitly convert them to factors, to indicate that they are categorical variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nd <- read_csv(\"https://data.dataliteracy.cc/simulated/practice_data.csv\") |>\n        mutate(experiment_group = as.factor(experiment_group),\n               np_subscription = as.factor(np_subscription)) |>\n        select(id, experiment_group, np_subscription, trust_t1, trust_t2)\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 600 × 5\n      id experiment_group np_subscription trust_t1 trust_t2\n   <dbl> <fct>            <fct>              <dbl>    <dbl>\n 1     1 control          no                  2.5      2   \n 2     2 control          yes                 4        4   \n 3     3 negative         no                  3        1   \n 4     4 negative         no                  3.75     1.75\n 5     5 control          no                  6        6.25\n 6     6 control          yes                 5.5      7   \n 7     7 negative         no                  4        3.75\n 8     8 control          yes                 5.5      5.25\n 9     9 positive         yes                 6.75     6.75\n10    10 control          yes                 4.75     3.75\n# ℹ 590 more rows\n```\n\n\n:::\n:::\n\n\n### One-way ANOVA\n\nIn one-way ANOVA we compare the means of a dependent variable between two or more groups in a single independent variable.\nWe can use this to test the main question of our experiment: whether the movie (*experimental_group*) has an effect on the trust in journalists (*trust_t2*).[^4]\n\n[^4]: We're using the trust score *after* watching the movie.\n    It is *ok* to ignore the trust score before watching the movie, because we've randomly assigned participants to the different groups.\n    This means that the trust score before watching the movie should be the same in each group.\n    However, as we'll show below, we could also use a repeated measures ANOVA to compare the trust score before and after watching the movie.\n\nWe use the `aov_car` function from the `afex` package to fit the ANOVA model.\nThe formula that we use in this function is, as usual, `dependent_variable ~ independent_variable`.\nHowever, we also need to specify the unique user id (`id`) using the `Error` function.\nThis way we explicitly clarify that each row in the data belongs to a unique participant in the study, which prevents you from mixing up between-subjects and within-subjects effects (more on this in the *repeated measures* section) So the full formula is `dependent_variable ~ independent_variable + Error(id)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm = aov_car(trust_t2 ~ experiment_group + Error(id), data=d)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: trust_t2\n            Effect     df  MSE         F  ges p.value\n1 experiment_group 2, 597 2.25 26.26 *** .081   <.001\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nWhen we print the output of the `aov_car` function, we get the main results of the ANOVA test.\nIn this one-way ANOVA we have a single independent variable, which is the `experiment_group`.\nThe output shows us the results of the F-test ($F_{2, 597} = 26.26, p < 0.001$) which tells us that the difference between the groups is **significant**.\nIn other words, the movie that participants watched had a significant effect on their trust in journalists.\n\nWe also get an $eta^2$ (eta squared) value in the `ges` column (generalized eta squared[^5]), This is a measure of **effect size** that tells us how much variance in the dependent variable is explained by the independent variable (similar to the $R^2$ value in regression).\n\n[^5]: The generalized $eta2$ is a generalization of the (partial) $eta2$ value that is often reported in ANOVA output.\n    It was proposed by @olejnik03 because regular partial $eta2$ values can be misleading when comparing between studies with different designs.\n    Specifically, it allows taking into account whether factors in the model are *experimentally manipulated* or *observed*.\n    In the **When factors are observed** subsection below we show how to specify this in the `aov_car` function.\n\n::: {.callout-note title=\"Comparing between groups\" collapse=\"true\"}\nThe $eta^2$ and F-test only tell us that there is a difference between the groups, but not *where* the difference is.\nTo compare bewteen the groups, we can first of all look at their means.\nFor this we'll use the `emmeans` function from the `emmeans` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeans = emmeans(m, \"experiment_group\")\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n experiment_group emmean    SE  df lower.CL upper.CL\n control            4.44 0.106 597     4.24     4.65\n negative           3.68 0.106 597     3.47     3.89\n positive           4.73 0.106 597     4.52     4.94\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nNow we can see that the lowest trust score is in the *negative* group, and the highest in the *positive* group.\nHowever, we do not yet know whether the diffences between all the groups are significant.\nIt could be that the *positive* group is significantly higher than the *negative* group, but not significantly higher than the *control* group.\nTo test this we can use the `pairs` function to get the pairwise comparisons for the means we just computed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast            estimate   SE  df t.ratio p.value\n control - negative     0.765 0.15 597   5.095 <0.0001\n control - positive    -0.287 0.15 597  -1.915  0.1354\n negative - positive   -1.052 0.15 597  -7.010 <0.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\nHere we see all possible combinations of groups.\nThe **control - negative** (control *minus* negative) row tells us how much the trust score in the control group is higher than in the negative group, and whether this difference is significant.\n\nFinally, we can visualize the results.\n`afex` has a built-in plot function (afex_plot), but throughout this book we often use the flexible `plot_model` function from the `sjPlot` package, and we can use this here as well!\nWe can get the linear model from the `aov_car` output using `$lm`, and then use the `plot_model` function to visualize the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_model(m$lm, type='pred', terms='experiment_group')\n```\n\n::: {.cell-output-display}\n![](19-anova_files/figure-html/one-way-anova-5-1.png){width=672}\n:::\n:::\n\n:::\n\n#### *Experimental* versus *observed* factors\n\nIn the previous example our independent variable was *experimentally manipulated*: we randomly assigned participants to the three groups.\nAccordingly, any effects that we find are likely to represent causal relationships.\nIf people with different opinions about journalism were randomly distributed over the groups, we can be confident that the differences we find after showing them different movies are due to the movies themselves.\n\nHowever, in some cases we might have an independent variable that is *observed*, meaning that we did not manipulate it, but only *observed* a value that was already there.\nThis is the case for variables like *age* and *gender*, and in our case also for *np_subscribed* (whether participants have a newspaper subscription).\n\nWhen factors are observed, it has two implications for the ANOVA test:\n\n-   **Causality**. It limits the ability to make causal inferences about the effect of the independent variable on the dependent variable.\n-   **Effect size**. We need to correct the $eta^2$ value to get more reliable effect sizes. The `afex` package does this automatically for us by using the generalized $eta^2$ value (`ges` column in the output).However, we do need to tell it when a factor is observed, using the `observed` argument in the `aov_car` function.\n\nLet's see how this works in practice, using the `np_subscription` variable as an observed factor.\nWith `observed='np_subscription'` we tell the `aov_car` function that the `np_subscription` variable is an observed factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_car(trust_t2 ~ np_subscription + Error(id), observed='np_subscription', data=d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: trust_t2\n           Effect     df  MSE         F  ges p.value\n1 np_subscription 1, 598 2.33 30.43 *** .048   <.001\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nIn this case our results only tell us that there is a significant difference between people with and without a newspaper subscription.\nWe cannot conclude that this is because having a newspaper subscription causes people to trust journalists more.\nWe are no longer certain about the order of the effect (trust in journalists might also cause people to get a newspaper subscription), and there can be confounding variables that influence both (e.g., education level, socio-economic status).\n\n### Two-way ANOVA\n\nIn a two-way ANOVA we compare the means of a dependent variable between two or more groups in two independent variables.\nTo demonstrate this we'll use the `np_subscription` variable as a second independent variable.\n\nThe formula for a two-way ANOVA is `dependent_variable ~ independent_variable_1*independent_variable_2 + Error(id)`.\nThe `*` symbol is a shorthand for including both the main effects and the interaction effect between the two independent variables.\nNote that we also again specify that `np_subscription` is an observed factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm = aov_car(trust_t2 ~ experiment_group*np_subscription + Error(id), \n            observed='np_subscription', data=d)\n```\n:::\n\n\nNow our output shows three F-tests: one for the main effect of `experiment_group`, one for the main effect of `np_subscription`, and one for the interaction effect between the two.\nWe also get three $eta^2$ values, one for each effect, which tell us how much variance is explained by each effect.\n\n::: {.callout-note title=\"Comparing between groups\" collapse=\"true\"}\nWe can again use the `emmeans` function to get the means for each group.\nLet's visualize the results first to get a better idea of how the two independent variables interact to affect the trust in journalists.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_model(m$lm, type='pred', terms=c('experiment_group', 'np_subscription'))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• linetype : \"np_subscription\"\n• shape : \"np_subscription\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](19-anova_files/figure-html/two-way-anova-2-1.png){width=672}\n:::\n:::\n\n\nHere we see that the effect of `np_subscription` (having a newspaper subscription) mostly matters for the *negative* group.\nIt seems that overall people that watched a *negative* movie have a lower trust in journalists, but this is mostly true for people that do not have a newspaper subscription.\nIn other words, people that have a newspaper subscription might not be as affected by the negative movie.\n\nWe can now use the `emmeans` function to test these differences.\nTo see how the effect of `experimental_group` is different for people that do or do not have a newspaper subscription, we can look at means of the `experiment_group` variable **conditional on** (`by`) the `np_subscription` variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeans = emmeans(m, 'experiment_group', by='np_subscription')\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnp_subscription = no:\n experiment_group emmean    SE  df lower.CL upper.CL\n control            4.09 0.160 594     3.78     4.41\n negative           2.88 0.151 594     2.59     3.18\n positive           4.71 0.150 594     4.42     5.01\n\nnp_subscription = yes:\n experiment_group emmean    SE  df lower.CL upper.CL\n control            4.68 0.132 594     4.42     4.94\n negative           4.33 0.137 594     4.06     4.60\n positive           4.75 0.138 594     4.48     5.02\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\npairs(means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnp_subscription = no:\n contrast            estimate    SE  df t.ratio p.value\n control - negative    1.2093 0.220 594   5.497 <0.0001\n control - positive   -0.6194 0.219 594  -2.830  0.0133\n negative - positive  -1.8286 0.213 594  -8.587 <0.0001\n\nnp_subscription = yes:\n contrast            estimate    SE  df t.ratio p.value\n control - negative    0.3532 0.190 594   1.859  0.1516\n control - positive   -0.0649 0.191 594  -0.340  0.9383\n negative - positive  -0.4181 0.195 594  -2.149  0.0811\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\nWe can now compare how the movie affects the trust in journalists, while taking into account how this is conditional on whether people have a newspaper subscription.\n\nLikewise, we could also compare how the newspaper subscription affects the trust in journalists, while taking into account how this is conditional on the movie that people watched.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeans = emmeans(m, 'np_subscription', by='experiment_group')\nmeans\npairs(means)\n```\n:::\n\n\nAnd finally, we could also compare between ALL the groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeans = emmeans(m, c('experiment_group', 'np_subscription'))\nmeans\npairs(means)\n```\n:::\n\n:::\n\n## Conditions and assumptions\n\nANOVA is a parametric test, which means that it makes assumptions about the data.\nIf these assumptions are violated, the results of the ANOVA can be unreliable.\nThe most important assumptions are:\n\n1.  **Normality**. The dependent variable should be normally distributed in each group.\n2.  **Homogeneity of variance**. The variance of the dependent variable should (approximately) be equal in each group.\n3.  **Independence**. Observations should be independent of each other.\n\nHere we will only discuss the assumption of **homogeneity of variance**, because it is more specific to ANOVA.\nFor the other assumptions, which are more general to linear models, we refer to the [regression tutorial](18-linear-regression.qmd).\nIf you have not yet learned about regression, you can ignore the details of these other assumptions for now.\n\n### Homogeneity of variance\n\nHomogeneity of variance means that the variance of the dependent variable should be (approximately) equal in each group.\nIn our one-way ANOVA example, this means that the variance of the trust score should be equal in the *control*, *positive*, and *negative* groups.\n\nWe can test this with the Levene's test, which is a test for homogeneity of variance.\nThe null hypothesis of the Levene's test is that the variance is equal in each group.\nIf the p-value of the test is less than 0.05, we reject the null hypothesis and conclude that the variance is not equal in each group.\n\nTo perform the Levene's test we can use the `leveneTest` function from the `car` package.\nTo test whether the variance of the trust score (dependent variable) is equal in each group of the independent variable, we use the formula `dependent_variable ~ independent_variable`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nleveneTest(trust_t2 ~ experiment_group, data=d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   2  0.8322 0.4356\n      597               \n```\n\n\n:::\n:::\n\n\nIn this case the Levene's test is not significant, which means that we can assume that the variance of the trust score is sufficiently equal in each group.\n\nFor two-way anova, we can also perform the Levene's test for each combination of the two independent variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(trust_t2 ~ experiment_group*np_subscription, data=d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   5  0.6001 0.6999\n      594               \n```\n\n\n:::\n:::\n\n\n#### What if the variance is not equal?\n\nIf Levene's test is significant, we would need to look more carefully into the variance across groups.\nANOVA is fairly robust to violations of the assumption of homogeneity of variance, but if the variance is very different between groups, the results of the ANOVA can be unreliable.\n\nSo how much difference in variance is too much?\nOne strategy is to look at the ratio of the largest to the smallest variance across the groups.\nA common rule of thumb is that this ratio should not be more than 3.[^6]\nHowever, note that this is just a rule of thumb, and if the sample size is small (less than 30 per group), or the groups are very unbalanced (i.e. one group has much more observations than the others), it is better to be more conservative.\n\n[^6]: By 'rule of thumb', we mean that it's a general guideline, and not a number that is set in stone.\n    Different authors have also proposed different values for this ratio.\n    One source for the 3:1 ratio is @dean00.\n    There is also Hartley's Fmax test, which is a more formal test that looks at the ratio of the largest to the smallest variance, and can take sample size and number of groups into account.\n    However, this test is in turn sensitive to normal distribution of data, and requires groups to be balanced.\n    Ultimately, there is no simple solution answer to the question \"how much difference in variance is too much?\".\n\nIn any case, it is always a good starting point to look at the sample size and variances across groups to see where potential problems might be.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars = d |>\n  group_by(experiment_group, np_subscription) |>\n  summarize(n = n(), variance = var(trust_t2)) \n\nvars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n# Groups:   experiment_group [3]\n  experiment_group np_subscription     n variance\n  <fct>            <fct>           <int>    <dbl>\n1 control          no                 81     2.25\n2 control          yes               119     1.89\n3 negative         no                 90     1.76\n4 negative         yes               110     2.15\n5 positive         no                 92     1.99\n6 positive         yes               108     2.33\n```\n\n\n:::\n\n```{.r .cell-code}\n## ratio of largest to smallest variance\nmax(vars$variance) / min(vars$variance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.32406\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nIn this case we have quite a lot of observations in each group, so if the ratio of the largest to the smallest variance ($S_{max}^2 / S_{min}^2 = 2.33 / 1.76 =  1.32$)[^7] is less than 3, we can assume that the variance is sufficiently equal in each group (and we already know that the Levene's test is not significant).\n\n[^7]: The $S_{max}^2$ and $S_{min}^2$ are the largest and smallest variance across the groups, which you can look up in the data frame above.\n    Note that $S^2$ is just the mathematical notation for variance ($S$ is the standard deviation, so $S^2$ is the variance).\n\nBut what if the homogeneity of variance assumption *is* violated?\nOne option would be to use a different model, like ANOVA with Welch's correction, or a non-parametric test like the Kruskal-Wallis test.\nBut perhaps more importantly, if you do find such strong differences in variance, you should look more closely at the data and think about what might be causing these differences.\nWhy is the variance higher in one group than in the other?\nIs there perhaps a confounding variable or moderator that you have not yet taken into account?\nPerhaps an experimental treatment was not applied correctly, or it might only have an effect in a specific subgroup of participants.\n\nMost importantly, do not think of testing these assumptions as a *hurdle* that you need to pass before you can use ANOVA.\nAt the end of the day, the purpose of statistics is to help us better understand our data.\nIf you find that your data does not meet the assumptions of ANOVA, this is not a failure, but an observation in itself that might warrant exploration.\nWhen in doubt, you can still use ANOVA, as long as you're transparent about the assumptions that are violated, and exert caution in your interpretation of the results.\n",
    "supporting": [
      "19-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}